language: node_js
node_js:
  - "10.15.0"
cache:
  directories:
    - node_modules
env:
  - CI=true
script:
  - yarn pub:docs
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: storybook-static
  on:
    branch: master
